### ISSUE TITLE
Reign In Hell Progress Roadmap

### ISSUE THREAD

**Issue by cartag** [MrJacob252/reigninhell#2]
- [x] Create categories for Lesser, Greater, Superior (L/G/S) demons
- [x] Modify default Force to include sections for L/G/S demons
- [x] Separate out Minion Demons into L/G/S to their own SSEs
- - [x] Include Primary Categories for each L/G/S demon
- - [x] L
- - [x] G
- - [x] S
- [x] Create RSEs for each L/G/S demon
- - [x] L
- - [x] G
- - [x] S
- [x] Add SSEGs for Essences and Relics to each Minion demon (already implemented on Leaders and Devouts)
- [x] Create SSE for "Lords of Hell Free Minion" with checkbox to change cost of model to 0 souls
- - [x] Include link to "Lords of Hell Free Minion" to each L demon
- [x] Adjust Evolution section for demons with an XP section on a per unit basis
- [x] Implement Soul Loss stat modifications
- [x] Remove "([Move], [Life], [Combat] are automaticaly increased in demon's profile by Battlescribe)" from all minion demon evolutions
- - [x] Stat lines in print out view will show if the demon has its stats modified
- [x] Convert profile modifications to Modification groups for demons that have more than one stat adjusted per Evolution

This is all I can think of so far, I'll add to it as I find things.
